### PR TITLE
OIDC Custom Scopes

### PR DESCRIPTION
**Pull request by rmathis**
This feature adds the ability to create custom scopes to an OIDC service, rather than being limited to the predefined values.

Screen Shot 2021-08-11 at 8 41 18 AM
Screen Shot 2021-08-11 at 8 41 24 AM

### CODE REVIEW

**Comment by mmoayyed** [comment]
Do you know if the app has the ability to auto-list custom scopes that may have already been defined in the configuration? If I have a "CustomScope" defined in the config (or via the discovery profile), does that show up in the app as a selectable option?

**Comment by mmoayyed** [comment]
My comment above is certainly not a blocker; just a nice-to-have if you wanted to something to work on. Otherwise this LGTM.

**Comment by rmathis** [comment]
> My comment above is certainly not a blocker; just a nice-to-have if you wanted to something to work on. Otherwise this LGTM.

I think its best to handle this in the future. I will create a ticket and assign it to myself.

**Comment by mmoayyed** [comment]
Sounds good.

**Pull request merged**
