### PR TITLE
Updated so tab-properties saves and displays

### PR DESCRIPTION
**Pull request by ahungerford-unicon**
Resolves JS issues breaking the page when adding properties on save for the Properties tab when editing a service.

### CODE REVIEW

**Comment by rmathis** [comment]
LGTM

**Review by rmathis — APPROVED** [review]

**Comment by mmoayyed** [comment]
Can you update the PR description to explain how "Also added fix to display the form attributes properly." works? What is the fix, and what was the issue exactly?

**Comment by rmathis** [comment]
> Can you update the PR description to explain how "Also added fix to display the form attributes properly." works? What is the fix, and what was the issue exactly?

I believe that has since been resolved by another pull request, as the change has disappeared from the diff. Adam's branch may have just needed to be fast-forwarded. Regardless I think that section of the comment is already resolved by this PR: https://github.com/apereo/cas-management/pull/186/files

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/apereo/cas-management/pull/186">bugfix: properties tab by rmathis · Pull Request #186 · apereo/cas-management</a></strong></div><div>Fixes an issue where the application where completing the Properties tab causes saving a service to fail.</div></blockquote>

**Comment by mmoayyed** [comment]
Gotcha. thanks for clarifying. I updated the description.

**Pull request merged**
