### PR TITLE
Added Configuration of properties

### PR DESCRIPTION
**Pull request by tsschmidt**
For planned changes we will need to add new fields to ManagementWebappProperties.  This branch and PR in its current form is in no way the correct means to do this.  A real solution will require a refactor to remove ManagementWebappProperties from the CAS Server and most likely moving other properties to an api project.  This is here now to facilitate discussion and provide a means to continue development on features.

### CODE REVIEW

**Comment by tsschmidt** [comment]
[Refactor Configuration of Properties](https://trello.com/c/pzwNwoom/20-refactor-configuration-of-properties)

**Comment by mmoayyed** [comment]
> A real solution will require a refactor to remove ManagementWebappProperties from the CAS Server and most likely moving other properties to an api project.

I think this is what we should shoot for. I am in the process of a cleanup to remove circular dependencies as much as possible to further break the codebase down, enable annotation processing, etc and I think as part of this effort, I will be able to execute that extraction so that the management app can own its own properties more successfully.

I think the more difficult/interesting question has to deal with how to load properties here without code duplication, with the same degree of functionality. Probably can answer that better once the clean up is done.

**Comment by tsschmidt** [comment]
That sounds like exactly what is needed.  Let me know if there is a piece you want to look at or work on.

**Comment by mmoayyed** [comment]
I should have something to review soon.

A couple of notes up front:

A lot of the circular dependencies I am fixing were discovered as a result of me turning on annotation processing in IDEA, which is something required by Lombok (which should help reduce noise quite a bit). To get around the problem, (I did report the behavior to IDEA folks as well), I am breaking the modules into those that contain core classes of a given functionality and those that simply contain Configuration objects of those classes. This is a pattern recommended by boot as well where you have core modules and then starter modules. I didn't want to rename modules to match that pattern because that would break everyone's configuration so I have opted for a compromise where we might have `cas-server-core-logout-api` where the core code lives for logout ops and then `cas-server-core-logout` per usual which only contains the configuration beans for logout. A lot of this maneuvering simply is caused by carelessly referencing modules here and there which gradle is perfectly fine with, but annotation processing isn't and a lot of also deals with using test components of a module in a different module in such a way that confuses the processor.

I am not planning for any of this to go into 5.2 yet, since the changeset is too large and uncertain at this point. we can revamp and revise after the release.

**Comment by tsschmidt** [comment]
Closed in favor of PR #4

**Pull request closed without merging**
